chain_one_line_max = 100
comment_width = 100
condense_wildcard_suffixes = true
error_on_line_overflow = false
fn_call_width = 100
fn_single_line = true
format_strings = true
imports_indent = "Block"
match_pattern_separator_break_point = "Front"
max_width = 100
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
single_line_if_else_max_width = 100
struct_field_align_threshold = 30
where_style = "legacy"
wrap_comments = true
write_mode = "overwrite"
